{% extends "mainapp/errors/base.html" %}

{% block title %}
500 - Произошла внутренняя ошибка сервера.
{% endblock %}

{% block content %}
<div class="error-page">
    <h2 class="headline text-danger">500</h2>

    <div class="error-content">
        <h3><i class="fas fa-exclamation-triangle text-danger"></i> Произошла внутренняя ошибка сервера.</h3>

        <p>
            Данные были зафиксорованы.
            <br>
            Попробуйте <a href="{% url 'mainapp:index' %}">вернуться на главную страницу</a>.
        </p>
        </form>
    </div>
</div>
{% endblock %}